# Generated by Django 2.2.7 on 2019-11-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('pub_key', models.CharField(max_length=344, unique=True)),
            ],
        ),
    ]
