# Generated by Django 2.2.7 on 2019-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_key',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
