# Generated by Django 2.2.7 on 2019-11-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonceChallenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=30)),
                ('uid', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
